security:
  enable_authenticator_manager: true
  #http://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
  password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticateInterface: 'auto'
  #https://symfony.com/doc/corrent/sucurity.html#loading-the-user-the-user-provider
  providers:
      #used toreload user from session & other features (e.g. switch_user)
         app_user_provider:
           entity:
               calss: App\Entity\User
              property: email
  firewalls:
       dev:
           pattern: ^/(_profiler|wdt|css|images|js)/
           security: false
      main:
            lazy: true
            provider: app_user_provider

            # activate different ways to authenticate
            # https: //symfony.com/doc/current/security.html#-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            #swithc_user: true

      # Easy way to control access for large sections of your site
      # note: only the *first* access control that matches will be used
      access_control:
          # - { path: ^/admin, roles: ROLE_ADMIN }
          # - { path: ^/profile, roles: ROLE_USER }
         
        

            